Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/ml_collections/config_dict/config_dict.py", line 947, in __getitem__
    field = self._fields[key]
            ~~~~~~~~~~~~^^^^^
KeyError: 'grad_accum_steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/ml_collections/config_dict/config_dict.py", line 849, in __getattr__
    return self[attribute]
           ~~~~^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/ml_collections/config_dict/config_dict.py", line 953, in __getitem__
    raise KeyError(self._generate_did_you_mean_message(key, str(e)))
KeyError: "'grad_accum_steps'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/emiresenov/jaxrc/case0inv/main.py", line 38, in <module>
    app.run(main)
  File "/opt/anaconda3/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/anaconda3/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/Users/emiresenov/jaxrc/case0inv/main.py", line 33, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/Users/emiresenov/jaxrc/case0inv/train.py", line 41, in train_and_evaluate
    model = models.CaseZero(config, t_star)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emiresenov/jaxrc/case0inv/models.py", line 15, in __init__
    super().__init__(config)
  File "/opt/anaconda3/lib/python3.11/site-packages/jaxpi/models.py", line 222, in __init__
    self.state = _create_inv_train_state(config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/jaxpi/models.py", line 115, in _create_inv_train_state
    tx = _create_optimizer(config.optim)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/jaxpi/models.py", line 78, in _create_optimizer
    if config.grad_accum_steps > 1:
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/ml_collections/config_dict/config_dict.py", line 851, in __getattr__
    raise AttributeError(e)
AttributeError: "'grad_accum_steps'"
