Waiting for JIT...
Traceback (most recent call last):
  File "/Users/emiresenov/jaxrc/case0inv/main.py", line 38, in <module>
    app.run(main)
  File "/opt/anaconda3/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/anaconda3/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/Users/emiresenov/jaxrc/case0inv/main.py", line 33, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/Users/emiresenov/jaxrc/case0inv/train.py", line 50, in train_and_evaluate
    model.state = model.step(model.state, batch)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/jaxpi/models.py", line 195, in step
    grads = grad(self.loss)(state.params, state.weights, batch, *args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/jaxpi/models.py", line 148, in loss
    losses = self.losses(params, batch, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emiresenov/jaxrc/case0inv/models.py", line 65, in losses
    l, w = self.res_and_w(params, batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emiresenov/jaxrc/case0inv/models.py", line 48, in res_and_w
    r_pred = vmap(self.r_net, (None, 0))(params, t_sorted)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emiresenov/jaxrc/case0inv/models.py", line 39, in r_net
    R = params['params']['R']
        ~~~~~~~~~~~~~~~~^^^^^
KeyError: 'R'
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
