Waiting for JIT...
u0: Traced<ShapedArray(float32[], weak_type=True)>with<DynamicJaxprTrace(level=4/1)>
u0: Traced<ShapedArray(float32[], weak_type=True)>with<DynamicJaxprTrace(level=1/0)>
u_pred: Traced<ShapedArray(float32[30])>with<DynamicJaxprTrace(level=1/0)>, u_test: Traced<ShapedArray(float32[30])>with<DynamicJaxprTrace(level=1/0)>
Traceback (most recent call last):
  File "/Users/emiresenov/jaxrc/case0inv/main.py", line 38, in <module>
    app.run(main)
  File "/opt/anaconda3/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/anaconda3/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/Users/emiresenov/jaxrc/case0inv/main.py", line 33, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/Users/emiresenov/jaxrc/case0inv/train.py", line 62, in train_and_evaluate
    log_dict = evaluator(state, batch, u_ref)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emiresenov/jaxrc/case0inv/models.py", line 108, in __call__
    self.log_preds(state.params)
  File "/Users/emiresenov/jaxrc/case0inv/models.py", line 93, in log_preds
    plt.imshow(u_pred.T, cmap="jet")
  File "/opt/anaconda3/lib/python3.11/site-packages/matplotlib/pyplot.py", line 3346, in imshow
    __ret = gca().imshow(
            ^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/matplotlib/__init__.py", line 1465, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/matplotlib/axes/_axes.py", line 5751, in imshow
    im.set_data(X)
  File "/opt/anaconda3/lib/python3.11/site-packages/matplotlib/image.py", line 723, in set_data
    self._A = self._normalize_image_array(A)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/matplotlib/image.py", line 693, in _normalize_image_array
    raise TypeError(f"Invalid shape {A.shape} for image data")
TypeError: Invalid shape (30,) for image data
