Waiting for JIT...
Traceback (most recent call last):
  File "/Users/emiresenov/jaxrc/case0inv/main.py", line 38, in <module>
    app.run(main)
  File "/opt/anaconda3/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/anaconda3/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/Users/emiresenov/jaxrc/case0inv/main.py", line 33, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/Users/emiresenov/jaxrc/case0inv/train.py", line 50, in train_and_evaluate
    model.state = model.step(model.state, batch)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/jaxpi/models.py", line 198, in step
    state = state.apply_gradients(grads=grads)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/flax/training/train_state.py", line 103, in apply_gradients
    updates, new_opt_state = self.tx.update(
                             ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/optax/transforms/_combining.py", line 75, in update_fn
    updates, new_s = fn(updates, s, params, **extra_args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: scale_by_zoom_linesearch.<locals>.update_fn() missing 3 required keyword-only arguments: 'value', 'grad', and 'value_fn'
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
