Waiting for JIT...
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/ml_collections/config_dict/config_dict.py", line 947, in __getitem__
    field = self._fields[key]
            ~~~~~~~~~~~~^^^^^
KeyError: 'constants'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/ml_collections/config_dict/config_dict.py", line 849, in __getattr__
    return self[attribute]
           ~~~~^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/ml_collections/config_dict/config_dict.py", line 953, in __getitem__
    raise KeyError(self._generate_did_you_mean_message(key, str(e)))
KeyError: "'constants'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/esenov/Documents/GitHub/jaxrc/case0inv/main.py", line 38, in <module>
    app.run(main)
  File "/opt/anaconda3/lib/python3.12/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/anaconda3/lib/python3.12/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/Users/esenov/Documents/GitHub/jaxrc/case0inv/main.py", line 33, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/Users/esenov/Documents/GitHub/jaxrc/case0inv/train.py", line 50, in train_and_evaluate
    model.state = model.step(model.state, batch)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/jaxpi/models.py", line 195, in step
    grads = grad(self.loss)(state.params, state.weights, batch, *args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/jaxpi/models.py", line 148, in loss
    losses = self.losses(params, batch, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/esenov/Documents/GitHub/jaxrc/case0inv/models.py", line 58, in losses
    U_dc = self.config.constants.U_dc
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/ml_collections/config_dict/config_dict.py", line 851, in __getattr__
    raise AttributeError(e)
AttributeError: "'constants'"
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
